quarkus.http.port=8089

#TODO: change to env
quarkus.neo4j.uri=bolt://localhost:7687
quarkus.neo4j.authentication.username=neo4j
quarkus.neo4j.authentication.password=test

org.neo4j.migrations.packages-to-scan=org.tuvarna.migrations